                  cx = 50 + r.nextFloat()*Math.max(1,getWidth()-100);
                  cy = 190 + r.nextFloat()*Math.max(1,getHeight()-260);
                }

                postInvalidateOnAnimation();
              }

              @Override
              public boolean onTouchEvent(MotionEvent e) {
                if (e.getAction()!=MotionEvent.ACTION_UP) {
                  x=e.getX()-45;
                  y=e.getY()-45;
                }
                return true;
              }
            }
          }
          EOF

      - name: Compilar APK
        run: gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Mi-Juego-2D-APK
          path: app/build/outputs/apk/debug/app-debug.apk
